### ISSUE TITLE
dictionary entries are treated as IRIs or CIRIs

### ISSUE THREAD

**Issue by chrysn** [core-wg/coral#1]
The current -08 sets up dictionary entries as URIs (among other things), which would be made into a URI string when used in a relation position or into a CIRI list when used in a link target position; outside of RDF use most dictionary entries will only see one use, but an implementer can't know for sure.

This may be hot-fixed by having dictionary entries typed in their description (so a 1&rarr;"urn:...:foo" would only work in a link relation and 2&rarr;&lt;http:\//foo/fbar&gt; would only work in a target position), but I'd prefer a solution that just makes relations IRIs (see #2).

**Comment by ektrah** [comment]
Yes, I think we should be consistent and use I-D.ietf-core-href wherever a URI/IRI is encoded in CBOR.

The reason why link relation types are currently encoded as CBOR text strings is as follows: The only operation that a processor needs to perform on a link relation type is a byte-by-byte comparison. CBOR arrays don't indicate their lengths in bytes, so a processor first has to parse the whole array before it can make the comparison. A CBOR text string indicates its length in bytes and therefore can be compared much more efficiently.

**Comment by ektrah** [comment]
No, I don't want dictionary entries to distinguish between URIs/IRIs used as link relation types vs. link targets.
