### ISSUE TITLE
Better name for CIRIs

### ISSUE THREAD

**Issue by ektrah** [core-wg/coral#18]
The draft no longer references RFC 3987, so the "Internationalized" part of "Constrained Internationalized Resource Identifiers" is a bit confusing.

Constrained Resource Identifier?

CRI?

CiRI?

**Comment by chrysn** [comment]
CoRI? CoURI? CBRI ("seebree"; Constrained/Concise Binary xRI)?

**Comment by cabo** [comment]
CoRI sounds great (except maybe for CORI as in Criminal Offender Record information); alliterates with CoRAL.
CRI as in "dernier cri" works for me, too (except for Color Rendering Index).

**Comment by ektrah** [comment]
CRI: *see-are-eye*, to be in line with *you-are-eye* and *eye-are-eye*
