### ISSUE TITLE
Relations as IRIs

### ISSUE THREAD

**Issue by chrysn** [core-wg/coral#2]
Currently there are two encodings for URIs, literal URIs in textual relations and CIRIs in targets.

For any kind of semantic application (:= we describe our vocabularies using our vocabularies, for this purpose) it'd be convenient to have all in one "space".

"Just changing that" does not raise immediate compactness issues, as dictionary entries would stay as they are, and URIs would just be encoded differently (provided we can express all sane URIs, which we can't yet, see #3).

We might still want to think about whether we want to cater for having compact predicate names in the relation type, for example by allowing templating inside CIRIs (I'd rather not, that document is neatly separate), or having a dedicated base URI for the relations that can be updated with a rel-base directive – but I think that can be done later still after the simple solution is applied (that'd probably say that relation IRIs need to start with a scheme).

**Comment by chrysn** [comment]
From discussion: doing the extension step opens a few more ways to express the same thing (the base does not).

**Comment by ektrah** [comment]
The most common operation on a link relation type in a CoRAL document by far is comparing it byte-wise to a known search link relation type.

Any encoding of a link relation type where the bytes are not sequentially in the buffer and/or not length-prefixed (e.g., indefinite-length text strings, CIRIs) makes comparisons less optimal.

**Comment by ektrah** [comment]
Based on discussions with Dave, we should remove any reference to RFC 3987 from the CoRAL CBOR format.

**Comment by ektrah** [comment]
Yes, I think we should be consistent and use I-D.ietf-core-href wherever a URI/IRI is encoded in CBOR.

**Comment by ektrah** [comment]
We could turn CIRIs/CoRIs into [CBOR Sequences](https://tools.ietf.org/html/draft-ietf-cbor-sequence-02). That would allow a processor to determine the length of a CoRI in bytes without fully decoding it.

The cost is a slightly increased footprint due to the encoding of a larger number and the need to disambiguate CoRIs from regular byte arrays in CoRAL with a tag:

```cddl
CoRI-new = #6.TBD( bytes .cborseq CoRI-old )
```

**Comment by chrysn** [comment]
I think the proposal of using byte strings of CBOR sequences is a good idea, primarily because it allows to have CoRIs in relation positions (which this issue is originally about).

(When the href document has cleaned up CoRI reference vs. absolute CoRI, in relation positions we should probably limit it to (full) CoRIs and disallow CoRI references).

For CoRIs of byte length <23, the length should be the same as before, provided no tagging happens. (For longer ones we'd typically need an extra byte, but the benefits of being usable to have CoRIs in relation positions, for which byte-wise comparability and thus CBOR-sequence byte strings are a practical prerequisite, are worth it).

The parsing benefits might also be available in link-target use, where a CoRAL parser would not need to descend through the whole CoRI but could put a pointer to the CoRI-in-the-payload on the parsing stack, and only pull it apart if it actually finds an actionable node under it.

In CoRAL link-target positions, I'd rather not tag the CoRIs but tag the literals, ie.

    literal = bool / float / time / text / #6.TBDx( int / bytes )

and only tag literals (the tag would be named "CoRAL literal", and could be allowed for bool/float/time/text as well, which above just don't have it because they can't be a bytes CoRI nor an int dict reference).

The tag byte overhead might be further reduced by moving the disambiguation into the link itself, so rather than now where we have

    link = [2, relation-type, link-target, ?[*element]]
    link-target = something that might be tagged

we could have

    link-to-cori = [2, relation-type, link-target, ?[*element]]
    link-target = IRI / int

that would take a CoRI or dict reference to a CoRI, and

    link-to-literal = [12, relation-type, literal-target, ?[*element]]
    literal-target = bool / int / float / time / bytes / text

which would have the same semantics, but disambiguate between whether int/bytes are literals or CoRI / CoRI dict lookups. (Wiggling the naming around a bit would probably allow for dict lookups that have their type indicated in the dictionary, so that the link-to-literal is always a literal and the link-to-cori could be a literal if there is a literal in the dictionary).

Whether that makes sense (or instead the leading numbers could be abandoned in favor of tagging-only) is a matter best decided with the input from #52.
