### ISSUE TITLE
Context and Base URI for unsuccessful responses

### ISSUE THREAD

**Issue by chrysn** [core-wg/coral#23]
We may want to add text on the base URI in CoRAL documents that come back on an unsuccessful REST request.

Use case: https://github.com/core-wg/wiki/wiki/CoAP-FAQ / grep for "http://example.com/dbaccess/dict".

**Comment by ektrah** [comment]
Text proposed in https://github.com/ektrah/I-D/commit/9d518c7a3b9e3b6ac4a9649a5a4e1b41633eb0cd

cc @thomas-fossati @cabo

**Comment by ektrah** [comment]
Done in [draft-ietf-core-coral-01](https://datatracker.ietf.org/doc/draft-ietf-core-coral/01/).
