### ISSUE TITLE
Dictionaries: Values are Magic?

### ISSUE THREAD

**Issue by chrysn** [core-wg/coral#26]
Going through how the patterns recently being established in pubsub can be used to align RD and reef, a mechanism occurred to me that could make things simpler or terribly complicated:

Can a dictionary be defined in such a way that an expanded value is not constant for the dictionary, but expanded as a function its application context?

For example, could there be a dictionary that has a key for "the address from which the client is sending the request", so that the client can submit
```
#using iana
#using rd = ...
rt core.rd-registration
lt 3600
rd:base $CLIENT_ADDRESS {
    hosts </sensor>
    ....
}
```

I think that this is a bad idea, but if it spawns a plethora of other potential use cases (the only others I can think of are referring to the requested URI, and that can be solved using the wording of initial base and root context), maybe it becomes a thing.

Feel free to close this with "Resolution: Just No".

**Comment by ektrah** [comment]
Let's postpone this until we know of more potential use cases.

Closing for now, but feel free to reopen.

**Comment by chrysn** [comment]
Agreeing to keep this as "No" in CoRAL, but underneath CoRAL CBOR [may do it](https://github.com/cbor-wg/cbor-packed/issues/1).
