### ISSUE TITLE
Processing unknown directives

### ISSUE THREAD

**Issue by ektrah** [core-wg/coral#27]
@jimsch [notes](https://mailarchive.ietf.org/arch/msg/core/lj7WwfjVxJDmvsJm8ZQdP2145V4):

> New directives can also cause problems in the future because how do I deserialize an object when I find a directive I don't understand.

So we need to define how newer, unknown directives must be processed by older processors.

Options:

* silently ignore unknown directives
* error out when encountering an unknown directive
* both, by marking directives with a to-be-defined critical/elective bit

**Comment by ektrah** [comment]
All of the directives defined so far change the processing environment in some way. If we assume that future directives will do so as well, then it becomes difficult to process a document where the processor does not know how to update the environment. Of course, there may be parts of processing a document that are optional. But I think I'd keep this simple: A processor has to understand all the directives in a document and error out when encountering an unknown directive.

Thoughts?

cc @jimsch @chrysn @cabo

**Comment by jimsch** [comment]
I think that the only possible answer is to fail.  However that would seem to imply that there might be a need for negotiation of what directives are supported by the parser so they will not be sent.   I really do not like the idea of marking directives as being critical/optional for processing.

**Comment by ektrah** [comment]
Any ideas what possible future directives might be? At the moment, my plan is to extend the current set only very conservatively, if at all.

**Comment by cabo** [comment]
I would also assume we will introduce new directives sparingly.  The whole issue of versioning rears its ugly head...  And I don't think we'll need "negotiation".  But critical/elective is actually useful in a data format.

**Comment by jimsch** [comment]
One directive that I could easily see is some type of dictionary directive so that it could be cached without having to try and query for it.  Another possibility would be something similar to what is being done over in 6TiSCH(?) where one could define a starting structure from which only differences are going to be published.

**Comment by chrysn** [comment]
Any new directives that I thought of so far had to do with compression. Would it make sense to white-list directives based on the dictionary? (A la "If you know this dictionary, you also have to be able to process those directives"). That would make a "fail unknown directives" outcome of this issue easier to work with.

**Comment by jimsch** [comment]
I could see a new type of form being defined at some point in the future.  I am not sure that the HTTP version of forms maps well into the IoT world.  (I am also not really a big user of either.)  I think we might end up with two different answers.  For some items, it would be tied to a dictionary version, but for others it is going to  have to be 'you can ignore me'.  Unless we want to get into assigning number games, I don't think that critical/elective can be easily encoded, I don't want to "waste" a byte on it.

**Comment by ektrah** [comment]
After discussing with @chrysn, we think that it's probably fine to keep it simple and require that all directives are "must understand". We need to add a sentence or paragraph on that to the draft.
