### ISSUE TITLE
Need a definition of simple string comparison

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#28]
This needs to be clarified more.  Specifically, does this mean that it is really a byte comparison or are there any other issues that could possibly pop up.  Part of me is worried about the issues of dealing with non-ASCII string where you might have to deal with locals and so forth when entering the string into code for the purposes of comparison.  Current locale, composite characters, canonicalization order of points.

**Comment by ektrah** [comment]
The [draft currently](https://tools.ietf.org/html/draft-ietf-core-coral-01#section-2.3) says:

```
These IRIs are only used as identity
tokens, though, and are compared using Simple String Comparison
(Section 5.1 of RFC 3987).
```

[Section 5.1 of RFC 3987](https://tools.ietf.org/html/rfc3987#section-5.1) says:

```
Applications using IRIs as identity tokens with no relationship to a
protocol MUST use the Simple String Comparison (see section 5.3.1).
```

[Section 5.3.1 of RFC 3987](https://tools.ietf.org/html/rfc3987#section-5.3.1) specifies the details of Simple String Comparison.

Do we need to say more?

The idea is basically that machines send vocabulary IRIs codepoint by codepoint as they are defined. If a machine sends the wrong codepoints, then it cannot expect a useful response.

When a human inputs vocabulary IRIs into a machine, however, then care must be taken that the input is converted into the correct codepoints. The [draft currently](https://tools.ietf.org/html/draft-ietf-core-coral-01#section-5.2) has some recommendations for minting IRIs to make this as painless as possible.

**Comment by jimsch** [comment]
I have no idea how I managed to miss the reference when I was reading it.
