### ISSUE TITLE
Express all URIs

### ISSUE THREAD

**Issue by chrysn** [core-wg/coral#3]
It Would Be Nice To™ be able to express all sane (ie. no IPv6 addresses with interface label, no HTTP URIs with user name and password) URIs that are around, including URIs of unknown schemes that may or may not have a default port, file URIs and URNs.

The current construction ensures that URIs of known and supported protocols (coap*, http) are always in their normal form. That property can be preserved *for supported schemes*, whereas for unsupported schemes there's no telling anyway.

The rules would need to be relaxed to allow path-etc right after the host (to allow port-free schemes) and right after the scheme (to allow URNs); `file:///` would be encoded as "scheme 'file', empy-literal authority, no port", `tel:+43-1-1234567` would be "scheme 'tel', path '+43-1-1234567'. The micrurus implementation already does that successfully (it has updated draft python code for composition and resolution).

Comparing IRIs could still be done on CBOR level, but require the validity criterion of default ports being absent to be fulfilled.

**Comment by ektrah** [comment]
This mostly depends on https://github.com/ektrah/coral/issues/9.

**Comment by ektrah** [comment]
We should compile a list of all URI schemes that should be supported and then study how much they differ from the CoAP URI syntax.

**Comment by chrysn** [comment]
My current take:

I'd like to have:
* http, coap, with their variants; user and password don't need to be supported
* URNs, tel, mailto, tag URIs (but there may be unsupported corner cases)
* file URIs (but with :///? :/?)

Not supporting non-UTF-8 URIs is OK.

Converting from IRIs is OK, but CoRIs can only faithfully reproduce IRIs after a round-trip through their URI form. (Equivalently, only URIs in UTF-8 form are supported).

All schemes that use ports need to have a known default port.

Not being able to support the difference between root path with and without the slash is probably OK. Not being able to support dot components in URIs that would be OK as well.

But I'll add a list of concrete examples later.

**Comment by chrysn** [comment]
Samples of URLs I'd like to express (from processed RDF files, with some modifications), and in the second paragraph examples I think are sane from 3986:
```
http://www.w3.org/2003/01/geo/wgs84_pos#lat
mailto:me@example.com
xmpp:me@example.com
http://dbpedia.org/resource/🐺
tag:me@example.com,2006-09-06:4816#p0823
file:///home/usernäme/test.coral

ftp://ftp.is.co.za/rfc/rfc1808.txt
http://www.ietf.org/rfc/rfc2396.txt
ldap://[2001:db8::7]/c=GB?objectClass?one
mailto:John.Doe@example.com
news:comp.infosystems.www.servers.unix
tel:+1-816-555-1212
telnet://192.0.2.16:80/
urn:oasis:names:specification:docbook:dtd:xml:4.1.2
```

Some more exotic cases (nice to have) should be convertible easily (ie. without any further rules):

```
tel:863-1234;phone-context=+1-914-555
ftp://myname@host.dom/%2Fetc/motd;type=a
file:/home/usernäme/test.coral
urn:example:1/406/47452/2
tag:timothy@hpl.hp.com,2001:web/externalHome

```

URI examples I think is OK if we can't support them, even though they are not deprecated:

```
ftp://cnn.example.com&story=breaking_news@10.0.0.1/top_story.htm
xmpp://guest@example.com/support@example.com?message
http://dbpedia.org/resource/%00
```

(But for userinfo, we might want to take a number in the type codes for it -- moving the first two URIs into the "nice to have" category.)

URI examples where I think it's OK that they get normalized into...

```
http://example.com/ -> http://example.com
sip:atlanta.com;method=REGISTER?to=alice%40atlanta.com -> sip:atlanta.com;method=REGISTER?to=alice@atlanta.com
```

Rationale:
* HTTP URIs, like CoAP URIs, have syntactic equivalence between empty path and "/" path ()
* The @ in the SIP query is basically sacrificing some of the allowed URI diversity (but a part that I guess is barely done right), and it is my untested impression that even this only example I found of optional percent encoding in URIs in an RFC would work just as well in its converted form.

    Usually, one may only replace percent-encoded characters with their actual characters [for unreserved](https://tools.ietf.org/html/rfc3986#section-2.3), but "@" is in pchar, which in addition to percent-encoded and unreserved also contains ":" and sub-delims. In a full URI, you can use anything that's not "unreserved" (but in particular sub-delims) to build your escapable separator, ie. just as we in CoAP and HTTP commonly allow URIs like `http://example.com/foo%2fbar/baz` to indicate a path composed of the components `foo/bar` and `baz` (not representable in most OSs, but hey, doesn't need to be filesystem-backed), they could build theirs as `http://example.com/foo%3bbar;baz` to have a semicolon-separated path of `foo;bar` and `baz`. Supporting one separator in CoRIs is easy (as pioneered in CoAP), supporting many would be hard, thus we acknowledge our constraints and normalizing everything that's not "/" (or "?" or "#") in paths and not "&" (or "#") in query components into its permitted ASCII form if exists or UTF-8 or percent-encoding otherwise.

(At some point, we should probably come up with guidance for implementers as to whether URIs that won't survive a round-trip through CoRIs should be accepted on input, rejected, or whether that "is up to the application". Empty-path-slash-stripping might be more acceptable than semicolon-overescape-removal).

**Comment by ektrah** [comment]
(Note to my future self: Check security issues relating to agents blindly following links to `//localhost` and `file:` URIs.)

**Comment by chrysn** [comment]
There is one more practical example of not being able to express subtleties of escaped vs. unescaped sub-delims that might be more practical: Some ways of HTTP form submission use plus ('+') to replace space (' '), such that eg. a DuckDuckGo search query for `foo +bar` results in a query component `foo+%2Bbar`. A CoRI as we have it now (where any not necessarily escaped character is not escaped in the end) will not be able to express a search for anything containing a plus on a server that expects the plus to be percent-escaped.

I'd still put that in the bin of "It's OK that we can only express one form", as CoAP already can't express that distinction -- but if we do want to discuss it further, this is porbably the most realistic example to talk about.

**Comment by chrysn** [comment]
A real-world example of URIs with non-UTF8 components are the [query parameters used in BitTorrent](https://byzantinemysteries.wordpress.com/2017/10/30/bittorrent-tracker-protocol-examples/) -- they have binary hashes in there.

Given that such query parameters are not legal in CoAP (though I wouldn't be surprised if many implementations accepted them), I'd put this in the "Sorry, not supported by this subset" category.

**Comment by ektrah** [comment]
We're running into interesting problems for URIs without an authority component. For example, both

```
[(Option.SCHEME, 'foo'), (Option.HOST_NAME, 'bar')]
```
and

```
[(Option.SCHEME, 'foo'), (Option.PATH, ''), (Option.PATH, ''), (Option.PATH, 'bar')]
```

recompose to `foo://bar`.

**Comment by ektrah** [comment]
Possible solutions:
* forbid two empty-string PATH options after a SCHEME option
* forbid empty-string PATH options altogether
* forbid more than one PATH option after a SCHEME option
* ...

**Comment by ektrah** [comment]
> forbid two empty-string PATH options after a SCHEME option

This is annoying to implement.

> forbid empty-string PATH options altogether

This is annoyingly restrictive.

> forbid more than one PATH option after a SCHEME option

This doesn't allow URNs like `urn:example:1/406/47452/2`. (There are four `/`-separated path segments here: `example:1`, `406`, `47452`, and `2`.)

> recompose PATH options after a SCHEME option using : rather than / as the separator

This doesn't allow URNs like `urn:example:1/406/47452/2`. (There are two `:`-separated path segments here: `example` and `1/406/47452/2`. However, this would recompose to `urn:example:1%2F406%2F47452%2F2` since `/` is a reserved delimiter.)

**Comment by chrysn** [comment]
> forbid empty-string PATH options altogether

more narrowly, that might be "forbid emptiness in the first PATH option" or "forbid empty non-terminal PATH options" -- but both would rule out the new `file:/usr/bin` format.

i'd prefer to go for "forbid two consecutive empty-string PATH options" (with our without the "after a SCHEME option" restriction; the latter would be one more constraint but easier to rely on). that *is* annoying to implement, but i think that only strict validity checkers (the kind people would put into their firewalls to see that things are normalized -- an antipattern IMO but well it happens) and URI-converters (which ideally don't get implemented in constrained devices, and if so the constrained device won't consume them, so it may elide the check because it advertises the URI for illustration only).

**Comment by ektrah** [comment]
Another possible solution that just comes to my mind: We just fail the conversion to IRIs when a SCHEME option is followed by two zero-length PATH options. This would also allow us to extend the conversion to CRI references; just for some CRI references the conversion would fail.
