### ISSUE TITLE
Section 2.3 - description of links seems to be incorrect

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#31]
Version -01

The first paragraph says that a link is a triple.  In the next sentence it says that the nested list takes the place of the target attributes.  But the triple does not contain something call attributes.   I assume that it means to say _link target_ instead.  The addition of attributes is confusing.

**Comment by jimsch** [comment]
Later in section 3.1.2 - It builds up relation-type, a link-target and a body.   The assumption would be that the context is the current base.  However, I now have a a four item element not a three item element.

**Comment by ektrah** [comment]
I don't see any instance of the word 'triple' or 'three item element' in the document... Section 2.3 says that a link consists of a context, a relation type, and a target, and additionally nested elements.

It's an interesting question, though, if the nested elements are logically attached to the link or to the link target...

**Comment by jimsch** [comment]
That is not at all how I read the section.

OLD: 
A _link_ describes a relationship between two resources on the Web
   [RFC8288].  As defined in RFC 8288, it consists of a _link context_,
   a _link relation type_, and a _link target_. In CoRAL, a link can
   additionally have a nested list of zero or more elements, which take
   the place of link target attributes.

NEW:
A _link_ describes a relationship between two resources on the WEB [RFC8288].  
Links are defined in RFC 8288 as a _link context_, a _link relation type_, a _link target_, and optionally, _target attributes_.  
In CoRAL, the link target attributes are encoded as a nested list of zero or more elements.

If you really want the last sentence in the original that is fine, there is now a target attributes item for it to take the place of.



List is from section 2 of RFC822

**Comment by ektrah** [comment]
Maybe I’m trying to say to much with too few words in that paragraph. What I’m trying to say is:

* In RFC 8288, a Link is defined to consist of a context, a relation type, a target, and attributes. 
* In CoRAL, a Link is defined in the same way, except that it doesn’t have attributes. At all. 
* However, instead, it can have nested elements. Nested elements cover both the chaining of links that you can do in RFC 8288 by setting the anchor of one link to the target of another and the expression of resource metadata that you can do in RFC 8288 by putting  attributes.

**Comment by jimsch** [comment]
An put that way it is much clearer.  I would say yes you tried to be too terse.
