### ISSUE TITLE
How to encode an empty target

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#32]
Base on the text, it is not clear what the correct way to encode an empty/null URI using CBOR.  There are a number of different ways that I can see which might be correct.

null - the problem with this is that it says that the link target is an unidentified resource.  That is not the same thing as an empty resource.
empty array - I think that this is a legal CoRI value according to the core-href document.  I think that this is correct, but it is not at all clear.  Using this value makes it clear that it is a URI.

** It would probably be useful to change the text version so that the difference between an empty value and a value which should be used as a relative IRI ('_')

**Comment by chrysn** [comment]
On Sat, Nov 23, 2019 at 10:24:20PM -0800, Jim Schaad wrote:
> Base on the text, it is not clear what the correct way to encode an empty/null URI using CBOR.

What do you mean exactly, especially by "empty resource"?

That which is equivalent to a link to the relative reference
empty-string is the empty array in core-href.

null refers to a thing in the link graph we have no label for (what RDF
calls a blank node) -- a resource that may not even have a URI, or the
author of the CoRAL document doesn't know it or want to tell it or can't
express it; maybe it's even the anonymous resource that represents an
failed request's result.

**Comment by jimsch** [comment]
My confusion is based on what is done for the text version where a literal is used rather than something tagged as a URI.  If things are treated the same way then the CBOR value of null would have seemed to be correct.

**Comment by ektrah** [comment]
As currently specified, a link target can be a URI reference or `null` (or one of the other types). When the target is `null`, it's not a URI reference. When the target is a URI reference, it's not `null`. In the text format, URI references are written between `<` and `>`. `null` is written as `null` or `_`. In the CBOR format, `null` is encoded as `null` and URI references are encoded as an array. I'm confused where  the confusion is coming from :-)

If you say "encode an empty/null URI using CBOR", I assume you're referring to the [case](https://tools.ietf.org/html/rfc3986#section-4.2) where a URI reference matches the ABNF rule for `path-empty`. That would be written in the text format as `<>` and encoded in CBOR as an empty array. Does that clarify things? What should we write in the draft to make it more clear?

**Comment by jimsch** [comment]
In that case I think that my problem is something else.  I will need to go find some of your presentations or our discussions to figure out why I was thinking something as a reference URI and not a literal in some of the CoRAL documents that I have seen.

**Comment by ektrah** [comment]
Closing for now, but feel free to reopen.
