### ISSUE TITLE
What is the default PathType value?

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#33]
The document does not explicitly state what the PathType value is when it is omitted from the sequence.  Based on some of the code I am guessing that it is relative-path.  Should be explicitly stated.

**Comment by jimsch** [comment]
This is in the wrong repository, but I don't see the href one.

**Comment by ektrah** [comment]
Let's use this repository to track issues for both drafts.

**Comment by ektrah** [comment]
The `path.type` value is tricky when it's omitted from the sequence :-)

The term "default value" usually means that some value is implied when a value is not explicitly given. However, `path.type` does not always have an implied value when the option is not there. Sometimes the option is simply not there.

**Comment by jimsch** [comment]
Yes but [6, 'node'] needs to be either <node> or </node> in a consistent manner.    On the other hand [1, 'mailto', 6, 'john@example.com'] does not have any implied value because it does not make sense for the scheme.

**Comment by ektrah** [comment]
`[6, 'node']` is neither &lt;node&gt; nor &lt;/node&gt; :-)

As mentioned in the other thread, I'm making no attempt at specifying any kind of conversion between URI references and sequences of options when they're relative. All you can do with `[6, 'node']` really is to resolve it against a base URI. 

`resolve` is essentially a decompression function. Its counterpart is `relative`, essentially a compression function. As usual, the decompression function is fully specified in the draft. But since there are many different possible implementations for the compression function, the draft leaves finding an efficient function to the implementers. This might require reverse-engineering the decompression function a bit, but I see no ambiguity in how an omitted `path.type` should be handled by the `resolve` function.

**Comment by jimsch** [comment]
While I am doing some - I need to convert a string to a CIRI and back, that is not what I am looking at here.  I am trying to figure out what is going to happen.  If the authority is going to be the resolve and relative functions that is fine.  However, I believe that the algorithm you are laying out has made a decision on what it means for the path.type to be absent.

**Comment by ektrah** [comment]
`resolve` handles `path.type` like this:

```python
        if option == Option.HOST_IP:
          option = Option.HOST_NAME
        elif option == Option.PATH_TYPE:
          type = href[0][1]
          href = href[1:]
        elif option == Option.PATH:
          type = PathType.RELATIVE_PATH
          option = Option.PATH_TYPE
```

In other words: If the sequence of options starts with `path.type`, it’s the value of that option. If the sequence starts with `path`, it’s `relative-path`. Otherwise, it’s not relevant.

**Comment by jimsch** [comment]
And that means that it defaults to PathType.RELATIVE_TYPE if not present and you are on that path.  Putting that in the paragraph means that you don't need to search for that information.

**Comment by ektrah** [comment]
Are you looking for something like this?

> **path.type**
>
> Specifies the type of the URI path for reference resolution.  The option value is an integer in the range from 0 to 127, named as follows:
>
> 0  absolute-path
> 1  append-relation
> 2  append-path
> 3  relative-path
> 4  relative-path-1up
> 5  relative-path-2up
> 6  relative-path-3up
> 7  relative-path-4up
> ...
> 127  relative-path-124up
>
> In the resolve function, the option is handled as follows: If the sequence of options starts with a path.type option, the value of that option is used. If the sequence starts with a path option, the value relative-path is assumed. Otherwise, the value is not relevant.

That's just the Python code paraphrased in English, though. I'd rather not do that, because English is not unit-testable.

**Comment by chrysn** [comment]
Maybe it helps phrasing it differently: Do we need to have a path type code for "relative-path" at all? Ie. is there any CoRI reference [(path.type, RELATIVE_PATH), *x] that can't be expressed as [*x] more briefly?

**Comment by ektrah** [comment]
[(path.type, RELATIVE_PATH), *x] and [*x] are treated by `resolve` identically. But in the latter case, `resolve` needs the path.type value to be greater than `append-path` and less than `relative-path-1up` for this line:

https://github.com/core-wg/coral/blob/28884aeccd875a2a4d638b962437e221c77a5d63/binary/python/ciri/__init__.py#L85

So I thought, why make the code more complicated by making this value in a path.type option special?

**Comment by chrysn** [comment]
Suggested text:

For all practical purposes[1], a CoRI reference that starts with a path is equivalent the same CoRI reference prefixed with a path-type=relative-path item.

[1]: The *only* practical thing to do with a CoRI reference is resolving it; comparing them does not lead to reliable results, and displaying them as URI references may not be possible in all cases.
