### ISSUE TITLE
Compress IPv6 addresses

### ISSUE THREAD

**Issue by ektrah** [core-wg/coral#4]
In constrained RESTful environments, DNS names and also IPv4 addresses are used much less often than IPv6 addresses, which are comparatively the largest (128 bits). Is there a way to compress IPv6 addresses in some way? (ex.: xor the address with the UDP source and strip away leading zeros)

**Comment by chrysn** [comment]
This would be traded off against immediate comparability of CIRIs. (The compared CIRIs may come from different contexts).

Sounds to me like one of the optimizations to keep on the issue tracker, gather experience with the unoptimized version, and keep an eye out for applications where this saves more than 10% of the message size.

**Comment by ektrah** [comment]
Maybe:

```cddl
IPv6Address = bstr .size 16
            / [ bstr .size (0..15), bstr .size (0..15) ]
```

E.g., `2001:DB8::1` could be encoded either as `h'20010DB8000000000000000000000001'` (17 bytes)  or as `[h'20010DB8', h'01']` (8 bytes).

**Comment by cabo** [comment]
There is a draft for IPv6 addresses in CBOR, draft-ietf-cbor-network-addresses-04.txt -- that doesn't have any compression proposals (except for prefixes, where that would be obvious).  I think I'd rather stick with that status; 16 bytes is still better than the usual 36 or so for a hex/colon address.
