### ISSUE TITLE
Strictness of literal restrictions

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#40]
I have started doing to unit testing for my CoRAL implementation.  Based on this I started running into questions about just what CBOR value encodings are and are not encoded.  Some things might seem to be reasonable, for example a BigNumber tagging of 2 would seem to be reasonable, however I am not sure that something like a major-order array of values is reasonable.  Should only the most basic values be permitted (0, 1, 2, 3, 6.0, 6.2, 7.21, 7.22, 7.23, 7.25, 7.26, 7.27).

**Comment by ektrah** [comment]
I'm not sure if you're asking for clarification or making a suggestion...

The [CoRAL draft](https://tools.ietf.org/html/draft-ietf-core-coral-01#section-3) currently specifies the following CDDL:

```cddl
literal = bool / int / float / time / bytes / text / null
```

[RFC 8610](https://tools.ietf.org/html/rfc8610#appendix-D) specifies:

```cddl
false = #7.20
true = #7.21
bool = false / true

uint = #0
nint = #1
int = uint / nint

float16 = #7.25
float32 = #7.26
float64 = #7.27
float16-32 = float16 / float32
float32-64 = float32 / float64
float = float16-32 / float64

time = #6.1(number)
number = int / float

bstr = #2
bytes = bstr

tstr = #3
text = tstr

nil = #7.22
null = nil
```

So it seems the current set of CBOR types used is (0, 1, 2, 3, 6.1, 7.20, 7.21, 7.22, 7.25, 7.26, 7.27).

**Comment by jimsch** [comment]
I was going for clarification here.  I was not sure if you considered a BigNumber to be an integer value or not.  I am also a bit surprised by the fact that time only includes #6.1 and not #6.2, but that is because I did not ever pay attention to that section of the CDDL specification.  I know what to do here.  I'll re-open if I think additional text is needed.
