### ISSUE TITLE
Append relation is not motivated

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#41]
The document has no motivation for supporting append-relation as a path type.  I have no idea of why this would ever be used.   Both sides would need to be explained - relative and resolve - because currently I don't see this as satisfying the required relationship of reversal.

**Comment by ektrah** [comment]
This was based on the hunch that, e.g., a fridge at `<coap://example.com/>` might have a link of type “the link target is my temperature sensor” at `<coap://example.com/temperature>` and a link of type “the link target is my fridge light” at `<coap://example.com/light>`. However, the hunch was never validated, so this feature is a bit under specified at the moment.

As with all the other compression-related topics, I would like to make decisions based on numbers for some real-world documents. If it turns that this feature provides no advantage, I’m happy if it gets removed.

**Comment by ektrah** [comment]
Removed in 41e61ea.

Please note d3672fe.
