### ISSUE TITLE
Should the dictionary include both postive and negative integer values rather than just postive ones

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#42]
For the reason of doubling the dictionary space of "small" int values, should this be defined in terms of "int" rather than "uint"?

**Comment by ektrah** [comment]
I envision that implementations could benefit a lot from having the negative integers available for internal use.

**Comment by jimsch** [comment]
I am not sure that I understand your comment.  Does that mean that the CDDL should be modified to accept both signed and unsigned integers or are you thinking about negative integers in some other manner?

**Comment by ektrah** [comment]
I'm thinking of restricting the CDDL to the range 0..2<sup>31</sup>-1, so that implementations can use 32-bit signed integers and have the range -2<sup>31</sup>..-1 available for implementation-internal purposes.

**Comment by ektrah** [comment]
I'm closing this for now. Feel free to reopen if you disagree.

**Comment by jimsch** [comment]
I'll let this slide for now, but if this is permitted at all then TBD6(uint) needs to be TBD6(int) or something similar in the CDDL.
