### ISSUE TITLE
Don't allow for empty arrays in general

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#48]
I think that it should be changed so that "?[*foo]"  becomes "?[+foo]" so that empty arrays are not allowed except for the root document itself.  This is generally easier to parse and most likely easier to generate for small devices.  Additionally, it shrinks the document itself slightly.

**Comment by ektrah** [comment]
Yes, I think a reasonable generator would omit the array if it's empty.

What should a reasonable processor do when it encounters an empty array? Should it say "Uh, sorry, I cannot make sense of this document -- it contains an empty array that should have been omitted!" ...or should it just silently skip over it?

```diff
 if (array is present) and (array length > 0) then
    there are nested elements
+elif (array is present) and (array length == 0) then
+    raise error
 else
    there are no nested elements
 endif
```

**Comment by jimsch** [comment]
I would be willing to address this in 2119 language rather than in CDDL.

**Comment by ektrah** [comment]
"A generator [WOULD PROBABLY](https://tools.ietf.org/html/rfc6919#section-5) omit an empty array. A processor [MUST](https://tools.ietf.org/html/rfc2119#section-1) ignore an empty array." ? 😃

**Comment by jimsch** [comment]
A generator SHOULD omit an empty array in order to minimize the size of the document.  A process MUST accept an empty array.

**Comment by ektrah** [comment]
I'm not sure if reasonable implementations can be enforced like this... [RFC 2119](https://tools.ietf.org/html/rfc2119#section-6) notes:

> **6. Guidance in the use of these Imperatives**
>
> Imperatives of the type defined in this memo must be used with care and sparingly.  In particular, they MUST only be used where it is actually required for interoperation or to limit behavior which has potential for causing harm (e.g., limiting retransmisssions)  For example, they must not be used to try to impose a particular method on implementors where the method is not required for interoperability.
