### ISSUE TITLE
Allow for link targets to be specified as part of forms

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#49]
Allowing some link items such as security pointers for forms is something that needs to be considered.  Suggested new syntax would be:

form = [3, operation-type, submission-target, ?[*form-field], ?TAG([+elements])]

I was looking at some stuff and wanted to include pointers to the authorization mechanism for a form and found that I could not do so because these are not form fields but are links.  However there does not appear to be a way to combine these together.   Other options exist for doing this which might be better.

**Comment by ektrah** [comment]
I think I would just use form fields for this. The text in the current draft is probably be a bit too restrictive on the purpose of form fields. Would that work?

**Comment by chrysn** [comment]
I don't quite see the difference between the `elements` and the `form-field`s here. From how I view the form-fields, they are a bit oddly named and would better be called "form properties". *Some* of these form properties describe fields, but that's just a (form description language) specific predicate::

```coral
enqueue -> </enqueue> {
    formlang:build "json-object"
    formlang:field {
        formlang:key "song"
        formalang:out-of </songs>
    }
    sec:authorization-requirement </playlistsecurity>
}
```

What actually constitutes a field is up to the application; some applications would list the actual data items inside their form description individually, some might just link to a schema.

**Comment by jimsch** [comment]
I think that it makes sense to separate the concept of a link and the concept of a form field at some level.  If you are going to expand the idea what can go into a form field, then I am not sure that I understand the difference between a form field and an element and how one tries to make the decision of what goes into a form field.  Of course since I don't understand how I am supposed to use forms here I don't think that this matters at the moment.

**Comment by ektrah** [comment]
I think we can solve this by better explaining how to use forms 😃
