### ISSUE TITLE
Implied submission method requires out-of-band knowledge

### ISSUE THREAD

**Issue by ektrah** [core-wg/coral#50]
This is a problem when a FETCH processing engine (such as a resource directory) needs to match elements to the FETCH query and is not aware of the implied submission method for each operation type.

Proposed solution: The submission method defaults to POST when not specified, rather than to the method implied by the operation type.

**Comment by chrysn** [comment]
Note to self for when I visit this issue again and am confused: When queries are expected to consider the entailment set of the available information, either the query processor (eg. a coral reef) must know the entailment rules, or be provided with the entailment set and annotations on what is explicit and what is implied. Both are infeasible in the coral reef scenario, but queries a la "Give me a form from there that uses the POST method" are to be expected.

**Comment by ektrah** [comment]
> Proposed solution: The submission method defaults to POST when not specified, rather than to the method implied by the operation type.

Corollary: Everybody will use POST instead of DELETE, FETCH, etc. just to save 2 bytes.

**Comment by ektrah** [comment]
Implied elements are a problem in general for a generic FETCH engine.

For example, if you have a link relation type `foo` that implies a nested link of type `bar` with value `1` ...

```
foo </a> { }
foo </b> { bar 1 }
foo </c> { bar 2 }
```

... and you query for links of type `foo` that have a nested link of type `bar` with value `1` ...

```
MATCH  foo ANYTHING { bar 1 }
```

then a generic FETCH engine that is unaware of the implied defaults would return only links where the nested link is explicitly included:

```
foo </b> { bar 1 }
```

To get the link where the nested link is implied, you would have to query for that, too:

```
MATCH  foo ANYTHING { bar 1 }  OR  foo ANYTHING { UNDEFINED(bar) }
```

Or, alternatively, include the implied defaults in-band:

```
foo IMPLIES { bar 1 }
MATCH  foo ANYTHING { bar 1 }
```

(Of course, we're rapidly approaching the level of sophistication of SPARQL here, which is not the goal...)

**Comment by chrysn** [comment]
> Implied elements are a problem in general for a generic FETCH engine.

Yes.

Different applications may use different strategies, but we should
highlight the problem and offer a strategy to recomment to "most
applications".

My suggestion would be to have an easy way to express

> ```
> MATCH  foo ANYTHING { bar 1 }  OR  foo ANYTHING { UNDEFINED(bar) }
> ```

in the query language and recommend that route, but hope that we have
more data for a more substantial recommendation with first applications
(given we don't aim for a FETCH/PATCH from the start).

**Comment by ektrah** [comment]
So, it seems we can proceed with the implied submission method, but need to take this into consideration when designing the FETCH format (#19). I’m therefore closing this issue.
