### ISSUE TITLE
What is the context for elements of a form field

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#53]
The current text makes no sense.  

~~~
The nested elements, if any, MUST be processed in a fresh
   environment.  Both the current context and current base in this
   environment are initially set to the form field value of the
   enclosing form field.
~~~

But if you look at

~~~
[3, operation-type, submission-target [
    field1 "Hi Mom" [
         [2, link-type, <Hi>]
    ]
]
~~~

In this case the text says that the context should be set to "Hi Mom".

**Comment by chrysn** [comment]
It says something very similar about links:

> The nested elements, if any, MUST be processed in a fresh environment. Both the current context and current base in this environment are initially set to the link target of the enclosing link.

It might say something like this insttead:

> MUST be processed in a fresh environment. The current context is set to the link target (or form field value) [ No "initially", as there's no directive to change that ]. The current base is initially set to the link target (or form field value) if it is an IRI, and identical to the parent's base in all other cases [ which are literals, including NULL ].

**Comment by jimsch** [comment]
I had missed the fact that this could be an issue for links as well.  The text suggested is along the same lines as what I was thinking.

**Comment by ektrah** [comment]
PTAL: 6c9a0f8c743a227a5a098895c4ae6b7274e9dc37
