### ISSUE TITLE
Non-followable links

### ISSUE THREAD

**Issue by ektrah** [core-wg/coral#7]
IRIs are used in two ways in CoRAL: as globally unique identifiers for link relation types/operation types/etc., and as dereferencable identifiers for Web resources. When expressing resource metadata, we might want to use the former kind also in the position of a link target. We should consider if we want to add a single bit to a link to say whether it’s intended to be followed or not. 

(Is this important if applications generally follow only links they understand anyway? Will applications get setting the bit always right?)

**Comment by chrysn** [comment]
I think whether an application follows a link should depend on the client and on the relation type; if the rel is unknown, the application should not follow the target. For example, most applications will not follow a an "A is of type B" relation but only use B as an identifier, while they would follow an "A has its index of collection items at B" when they're using collections, and ignore "A has fnord B" if they don't know what a fnord is.

The cases I can think of where a CoRAL document wants to encourage following could be covered by describing the target, eg. if an application *does* know some kind of class description format, an "A is described at B" link can be useful to a client even if it doesn't know B yet; the CoRAL document can indicate that it'd make sense to dereference B by saying "B, which is of content format X".

Note that predicates / relation types are also IRIs an application can want to follow, but only applications that do reasoning / inference will ever dereference them.

**Comment by ektrah** [comment]
I'm closing this for now with no action. We can reopen this later if needed.

**Comment by chrysn** [comment]
Where we come across trouble teaching CoRAL as having URI-valued predicates that shouldn't always be dereferenced, we may take inspiration from how RDF vocabularies are shaped.

Look at http://xmlns.com/foaf/spec/ for example. All the information is there if you're in the RDF mindset to see the xmlns, but terms are always talked about with their local names, and examples consistently use `foaf:Agent` or similar terms. The equivalent of our "using" can be shown in some form of preamble, but the fact that all these terms are URIs is not emphasized towards audiences that don't come from a semantic web background.
