### ISSUE TITLE
Comparing CIRIs

### ISSUE THREAD

**Issue by ektrah** [core-wg/coral#9]
We need to decide whether we need to able to perform equality comparisons for  CIRIs.

Byte-wise equality comparisons (which would be the easiest for constrained devices) require that all CIRIs are fully normalized.

(Just dereferencing a CIRI, the most common operation, does not require normalization.)

Note that we need equality comparisons for Web origins with the current security model.

**Comment by ektrah** [comment]
If we use CIRIs to make authorization decisions (e.g., by listing them in CBOR-encoded ACLs), then CIRIs must be comparable.

**Comment by chrysn** [comment]
using ciris for that will matter; aif just came up in ace, and ciris (possibly path-absolute, unsure) fit nicely.

per-application requirements that uris of supported schemes (whichever in that app) must follow the scheme's normalization rules still makes sense imo.

**Comment by jimsch** [comment]
If we are going to allow for CoRIs to be included in a dictionary, then we need to be able to compare both absolute and relative CoRIs.

**Comment by ektrah** [comment]
I think it's pretty clear by now that we want to be able to test two CoRIs for equivalence. The open questions (with some impact on the design on CIRIs) is, whether we want to be able to test two CoRIs for equivalence where we don't understand the URI scheme(s). Currently, this *is* supported, because CIRIs are defined to support only URI schemes that have the same normalization rules as CoAP and because the port number must always be specified explicitly.

**Comment by chrysn** [comment]
Maybe we can limit the cases where normalization can not be decided to maliciously crafted CoRIs:

If we demand that the CoAP normalizations are done (trailing slash in root) and that default ports are always elided, the only case a schema-unaware comparator could wrongly find would be a difference between http://example.com/ and http://example.com:80/. The latter form, in CoRIs, could only be caused by an erroneous (and probably malicious) agent. As long as comparison is done in a whitelist-based manner, that's not an issue -- blacklists would need to be recommended against.

**Comment by chrysn** [comment]
Other comparison issues beside port:
* host name capitalization

**Comment by ektrah** [comment]
Comparison for CoRIs that do not start with a scheme is undefined / MUST NOT.

**Comment by chrysn** [comment]
> CoRIs that do not start with a scheme

Can we already start calling them "CoRI references", anticipating alignment with RFC3986?

**Comment by ektrah** [comment]
Yes. -coral-02 is doing that already. Just -href-02 is not there yet.

**Comment by jimsch** [comment]
If the scheme is required, does this mean that you will not be able to compare two relative URIs?  While there are more ways to encode these, it may be a useful thing to be able to say something about.

**Comment by ektrah** [comment]
Equivalence of relative references is really difficult to establish. For example, are `</foo/bar/baz>` and `<../baz>` equivalent? Yes, they are - if they're both relative to `<http://example.com/foo/bar/qux/>`. So IMO you'll always have to resolve a relative reference (i.e., decompress it) first before you can compare it.

**Comment by ektrah** [comment]
It seems [RFC 3986](https://tools.ietf.org/html/rfc3986#section-6.1) supports this:

> In testing for equivalence, applications should not directly compare relative references; the references should be converted to their respective target URIs before comparison.

**Comment by jimsch** [comment]
I think that the comment from RFC 3986 should discourage doing a bstr wrapping on and then comparing the encoded bstr.  One would not know if one was doing absolute or relative comparisons in this case.

**Comment by chrysn** [comment]
> I think that the comment from RFC 3986 should discourage doing a bstr
> wrapping on and then comparing the encoded bstr.

Identifying whether a reference is a (full) CoRI or an actually relative
CoRI reference should be rather simple. A (full) CoRI, assuming the
streaming-bstr format, always starts with 0x01 (scheme), and no other
does.

This is just as it is with URIs (can't compare relative references
either), just that unlike URIs where the criterion is roughly "the first
colon precedes the first slash", the criterion is easy.
